### ISSUE TITLE
Multistream is not practical

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#63]
Let `v1` a video stream and `a1` the respective audio stream and let `a2` another audio stream much shorter than `a1`.

If the streams are loaded in the following order:

1. `a2`
2. `v1` and `a1`

`a2` overlaps `a1` in the spectrogram, so we lost part of `a1`. It would be better to place the two audio streams on different spectrograms.

**Comment by rr-** [comment]
To challenge this point of view, what's the point of having multiple out of sync audio streams if you're still working with one subtitle list, tied to one specific timing?

**Comment by Luni-4** [comment]
In my case, I had a video with a song in Japanese, and the same song dubbed in English. The English audio was shorter than the Japanese one of three seconds. I wanted to insert the English subtitles on the Japanese song listening to the English song. So `v1` and `a1` are synced, but I was not interested if the two audio streams were minimally out of sync. But since `a1` and `a2` overlaps I couldn't apply my strategy.

**Comment by rr-** [comment]
I have introduced audio delays for this reason; we're still probably missing tempo to cater for sped up / slowed down streams.

Anyway the idea to refactor the UI so that new spectrograms can be created on demand for the audio streams of your choice is sweet and maybe I would like to see it in bubblesub, but I doubt I'll ever have the time to do it myself, plus it kind of violates the keep it simple rule. Plus it's not clear what to do with video, since syncing the audio would probably feature looking at both videos in some way, but we have took measures to separate audio from video due to the demand of having the ability to load the audio stream from a different file than the video file. Let me give you an example of what I'd like to eventually have –

I'm translating from Japanese, but I'm also using French dub to help with some muffled lines etc. However the French version for some reason (TV time slots?) is sped up by 10% thus gets out of sync all the time. I'd like to sync the audio streams with each other by looking for the same scenes in their respective video streams, and setting AV delay + tempo change in both streams. Maybe with dialogs that ask for time codes. Maybe with mouse gestures on two spectrograms. Maybe with a user script that compares video frames with cv2. I don't know, but whatever the choice, this use case is extremely difficult to model a good UI for, and I'm not sure if it's okay to put in many hours for such obscure feature. My idea was to at least prepare the API layer for this.

The other idea I would like is to have bubblesub support tabbed user interface, so I can load my Japanese video in tab 1, and French video in tab 2 where I have completely separate subtitle list. I believe this would be much more useful than dynamic spectrograms. But again I don't have the time or motivation to do this at this point in time.

**Comment by Luni-4** [comment]
> I have introduced audio delays for this reason; we're still probably missing tempo to cater for sped up / slowed down streams, but I don't think mpv has option to change tempo only for the audio stream. (This is available only via commands, there's no UI for this whatsoever.)

True, unfortunately. Anyway, the bubblesub UI can be updated easily, I could do that myself.

> Anyway the idea to refactor the UI so that new spectrograms can be created on demand for the audio streams of your choice is sweet and maybe I would like to see it in bubblesub, but I doubt I'll ever have the time to do it myself, plus it kind of violates the keep it simple rule. Plus it's not clear what to do with video, since syncing the audio would probably feature looking at both videos in some way, but we have took measures to separate audio from video due to the demand of having the ability to load the audio stream from a different file than the video file. 

To simplify the things, I think we shouldn't load more videos, but only the ONE we are working on. In this way, we could reduce the memory consumption also. In fact, one usually works with a single video at a time and changes only the audio streams to help himself with the translation. So a video must be synced only with the respective audio stream.
Practically I'm imagining this scenario: 
- A single video stream (the one bounded with the subs)
- The video's audio stream with the video bands associated in the main spectrogram
- *Discussing this point in the next quote*

>Let me give you an example of what I'd like to eventually have –
> 
> I'm translating from Japanese, but I'm also using French dub to help with some muffled lines etc. However the French version for some reason (TV time slots?) is sped up by 10% thus gets out of sync all the time. I'd like to sync the audio streams with each other by looking for the same scenes in their respective video streams, and setting AV delay + tempo change in both streams. Maybe with dialogs that ask for time codes. Maybe with mouse gestures on two spectrograms. Maybe with a user script that compares video frames with cv2. I don't know, but whatever the choice, this use case is extremely difficult to model a good UI for, and I'm not sure if it's okay to put in many hours for such obscure feature. My idea was to at least prepare the API layer for this.
> 
> The other idea I would like is to have bubblesub support tabbed user interface, so I can load my Japanese video in tab 1, and French video in tab 2 where I have completely separate subtitle list. I believe this would be much more useful than dynamic spectrograms, and it's much more straightforward – there is no room for questions of the form "how do we …?". But again I don't have the time or motivation to do this at this point in time.

I agree with the API layer, it would give much more freedom to the users. 

For what concerns the UI redesign, I agree that having lots of out-of-sync spectrograms wouldn't be practical, but perhaps we could set some limits. For example, a user can load only two alternative audio streams. In this way, we would have only two spectrograms to render, but we would incur in problems such as "I need three or more alternative audio streams"...

Perhaps adding the spectrograms under the subs grid and console could help to add more of them. Something like the timeline used for video editors. As a temporary solution obviously.

The tab option is pretty good, but it complicates a lot the code imho, so I wouldn't consider that for now.

**Comment by rr-** [comment]
Can this be closed in favor of #64  + #65 ?

**Comment by Luni-4** [comment]
I would say in favor of #65 and the Dock Widgets feature (would it ever be implemented??)

**Comment by rr-** [comment]
Let's create a new issue to track it but I'd say it's unlikely I'll touch it anytime soon

**Comment by Luni-4** [comment]
Closed in favor of #65 and #74
